name = "dubyah"
port = 80
# TODO: Un-comment this once live
#tlsPort = 443 
#tlsDir = "./tls"

plugins = [
	"github.com/vroomy-ext/jump-plugin@v0.19.0 as jump",

	"github.com/BrandenWilliams/dubyah/plugins/auth",
	"github.com/BrandenWilliams/dubyah/plugins/onboarding",
	"github.com/BrandenWilliams/dubyah/plugins/templates",
	"github.com/BrandenWilliams/dubyah/plugins/pages",
	"github.com/BrandenWilliams/dubyah/plugins/tasklists",

]

include = [
	"./routes/api",
	"./routes/pages.toml",
	"./routes/jspages.toml",
	"./routes/assets.toml",
	"./routes/404.toml",
]

[env]
mojura-sync-mode = "development"
