[[route]]
method = "GET"
httpPath = "/"
handlers = [
	"pages.Homepage",
]

[[route]]
method = "GET"
httpPath = "/TechSupport"
handlers = [
	"pages.TechSupport",
]

[[route]]
method = "GET"
httpPath = "/TaskManagement"
handlers = [
	"pages.TaskManagement",
]

[[route]]
method = "GET"
httpPath = "/Websites"
handlers = [
	"pages.Websites",
]

[[route]]
method = "GET"
httpPath = "/Resume"
handlers = [
	"pages.Resume",
]
