# Private Assets
[[group]]
name = "private"
#group = "private"
httpPath = "/"
handlers = [ 
   "jump.SetUserMW(true)",
]

# Private & Private Assets
# Private Assets
[[group]]
name = "publicandprivate"
httpPath = "/"
handlers = [
	"jump.SetUserMW(false,true)",
]

[[route]]
method = "GET"
group = "publicandprivate"
httpPath = "/"
handlers = [
	"pages.Homepage",
]

[[route]]
method = "GET"
group = "publicandprivate"
httpPath = "/techSupport"
handlers = [
	"pages.TechSupport",
]

[[route]]
method = "GET"
group = "publicandprivate"
httpPath = "/websites"
handlers = [
	"pages.Websites",
]

[[route]]
method = "GET"
group = "publicandprivate"
httpPath = "/resume"
handlers = [
	"pages.Resume",
]

[[route]]
method = "GET"
group = "public"
httpPath = "/login"
handlers = [
	"pages.LoginPage",
]

[[route]]
method = "GET"
group = "public"
httpPath = "/signup"
handlers = [
	"pages.SignUp",
]

# Task Management routes
[[route]]
method = "GET"
group = "publicandprivate"
httpPath = "/taskManagement"
handlers = [
	"pages.TaskListsManagement",
]

[[route]]
method = "GET"
group = "private"
httpPath = "/taskList/:entryID"
handlers = [
	"pages.TaskList",
	"jump.CheckPermissionsMW(tasklists,entryID)",
]
