[[group]]
name = "tasklists"
group = "api"
httpPath = "/tasklists"
handlers = []

[[route]]
method = "POST"
group = "tasklists"
httpPath = "/newList/:userID"
handlers = [
    "jump.CheckPermissionsMW(user,userID)",
    "tasklists.NewTaskList",
]

[[route]]
method = "POST"
group = "tasklists"
httpPath = "/newTask/:entryID"
handlers = [
    "jump.CheckPermissionsMW(tasklists,entryID)",
    "tasklists.AddNewTask",
]

[[route]]
method = "POST"
group = "tasklists"
httpPath = "/moveTaskUp/:entryID"
handlers = [
    "jump.CheckPermissionsMW(tasklists,entryID)",
    "tasklists.UpdateTaskPositionUp",
]

[[route]]
method = "POST"
group = "tasklists"
httpPath = "/moveTaskDown/:entryID"
handlers = [
    "jump.CheckPermissionsMW(tasklists,entryID)",
    "tasklists.UpdateTaskPositionDown",
]

[[route]]
method = "Post"
group = "tasklists"
httpPath = "/deleteTask/:entryID"
handlers = [
    "jump.CheckPermissionsMW(tasklists,entryID)",
    "tasklists.DeleteTask",
]

[[route]]
method = "Post"
group = "tasklists"
httpPath = "/deleteTaskList/:entryID"
handlers = [
    "jump.CheckPermissionsMW(tasklists,entryID)",
    "tasklists.DeleteTaskList",
]
